version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
  build:
    commands:
      - echo Building the application...
      - npm run build

      - echo Creating a ZIP file of the application...
      - zip -r facebook-clone.zip .

      - echo Uploading the ZIP file to S3...
      - aws s3 cp facebook-clone.zip s3://my-s3-bucket12332/facebook-clone.zip

      - echo Defining version label...
      - VERSION_LABEL=$(date +%Y%m%d%H%M%S)

      - echo Creating a new application version in Elastic Beanstalk...
      - aws elasticbeanstalk create-application-version --application-name Social_Media_Application --version-label $VERSION_LABEL --source-bundle S3Bucket=my-s3-bucket12332,S3Key=facebook-clone.zip

      - echo Updating Elastic Beanstalk environment...
      - aws elasticbeanstalk update-environment --application-name Social_Media_Application --environment-name SocialMediaApplication-env-1 --version-label $VERSION_LABEL
  post_build:
    commands:
      - echo Deployment to Elastic Beanstalk completed.

artifacts:
  files:
    - facebook-clone.zip
